version: "3.9"
services:
  app:
    build: ./src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/app:/app
      - /app/node_modules
    ports:
      - 3000:3000
    container_name: julia_app
    depends_on:
      - api
  api:
    build: ./src/api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/api:/api
      - /api/node_modules
    ports:
      - 8000:8000
    container_name: julia_api